// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH1KtXm02D7nEeBhVZqiSx9xoZ1a4k8pc',
    appId: '1:142745895006:web:6c9da5884ff3d9a2c134cf',
    messagingSenderId: '142745895006',
    projectId: 'waterly-3ad4f',
    authDomain: 'waterly-3ad4f.firebaseapp.com',
    databaseURL: 'https://waterly-3ad4f-default-rtdb.firebaseio.com',
    storageBucket: 'waterly-3ad4f.firebasestorage.app',
    measurementId: 'G-HTWE06TLX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwtG7G_m4agunb5nzwK8hqDX0kbw6lI8c',
    appId: '1:142745895006:android:f5b2f7dcd917de9dc134cf',
    messagingSenderId: '142745895006',
    projectId: 'waterly-3ad4f',
    databaseURL: 'https://waterly-3ad4f-default-rtdb.firebaseio.com',
    storageBucket: 'waterly-3ad4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcLSK_JiZuPvjbSBqjxyp1ErNtLG7em3k',
    appId: '1:142745895006:ios:0cd55d7ca01ca99ec134cf',
    messagingSenderId: '142745895006',
    projectId: 'waterly-3ad4f',
    databaseURL: 'https://waterly-3ad4f-default-rtdb.firebaseio.com',
    storageBucket: 'waterly-3ad4f.firebasestorage.app',
    iosBundleId: 'com.example.waterly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcLSK_JiZuPvjbSBqjxyp1ErNtLG7em3k',
    appId: '1:142745895006:ios:0cd55d7ca01ca99ec134cf',
    messagingSenderId: '142745895006',
    projectId: 'waterly-3ad4f',
    databaseURL: 'https://waterly-3ad4f-default-rtdb.firebaseio.com',
    storageBucket: 'waterly-3ad4f.firebasestorage.app',
    iosBundleId: 'com.example.waterly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH1KtXm02D7nEeBhVZqiSx9xoZ1a4k8pc',
    appId: '1:142745895006:web:647754c016de4525c134cf',
    messagingSenderId: '142745895006',
    projectId: 'waterly-3ad4f',
    authDomain: 'waterly-3ad4f.firebaseapp.com',
    databaseURL: 'https://waterly-3ad4f-default-rtdb.firebaseio.com',
    storageBucket: 'waterly-3ad4f.firebasestorage.app',
    measurementId: 'G-MN54SDTYYE',
  );
}
